# Generated by Django 4.0.6 on 2022-07-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
